id: P001693
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01514
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༤ ༼༡༣༽
  author: ''
  volumes:
    9b42eabd6a1a43b994bf803944bd56ed:
      image_group_id: I5814
      title: ''
      volume_number: 1
      total_pages: 217
      base_file: v001.txt
