id: P001693
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:04.189187
source_metadata:
  id: bdr:W00KG01514
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༤ ༼༡༣༽
  author: ''
  volumes:
    9b42eabd6a1a43b994bf803944bd56ed:
      image_group_id: I5814
      title: ''
      volume_number: 1
      total_pages: 217
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
